service: MovieApi-Infra
frameworkVersion: '3'

provider:
  name: aws
  region: eu-north-1
  profile: default
  stage: ${opt:stage, 'dev'}
  stackTags:
    Usage: ${self:service}
  tags:
    Usage: ${self:service}

resources:
  - ${file(./MoviesTable.yml)}
  - Outputs:
      TableName:
        Value: !Ref MoviesTable
      TableArn:
        Value: !GetAtt MoviesTable.Arn