service: MovieApi
frameworkVersion: '3'

provider:
  name: aws
  region: eu-north-1
  profile: default
  runtime: dotnet6
  stage: ${opt:stage, 'dev'}
  architecture: x86_64
  memorySize: 256
  timeout: 10
  logRetentionInDays: 7
  versionFunctions: true
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  stackTags:
    Usage: ${self:service}
  tags:
    Usage: ${self:service}
  apiGateway:
    minimumCompressionSize: 1024
  tracing:
    apiGateway: true
    lambda: true
  layers:
    - arn:aws:lambda:eu-north-1:702835727665:layer:honeycomb-lambda-extension-x86_64:9
  environment:
    LIBHONEY_DATASET: MovieApi
    LIBHONEY_API_KEY: ${ssm:/aws/reference/secretsmanager/dev/MovieApi/LIBHONEY_API_KEY}
    LOGS_API_DISABLE_PLATFORM_MSGS: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - xray:PutTelemetryRecords
            - xray:PutTraceSegments
            - xray:GetSamplingRules
            - xray:GetSamplingTargets
            - xray:GetSamplingStatisticSummaries
          Resource:
            - "*"
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
          Resource:
            - !GetAtt MoviesTable.Arn
            - !Join ["", [!GetAtt MoviesTable.Arn, "/index/*"]]

plugins:
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
    seed:
      test:
        sources:
          - table: MoviesTable
            sources: [./DynamoDb/MoviesTable.seed.json]

package:
  artifact: bin/Release/net6.0/MovieApi.zip

functions:
  GetMovie:
    handler: MovieApi::MovieApi.Functions.GetMovieFunction::HandleAsync
    events:
      - http:
          method: GET
          path: /movies/{movieId}
          authorizer: aws_iam
  UpdateMovie:
    handler: MovieApi::MovieApi.Functions.UpdateMovieFunction::HandleAsync
    events:
      - http:
          method: PUT
          path: /movies/{movieId}
          authorizer: aws_iam
          request:
            schemas:
              application/json:
                name: UpdateMovieRequest
                schema: ${file(Schemas/UpdateMovieRequest.schema.json)}
  DeleteMovie:
    handler: MovieApi::MovieApi.Functions.DeleteMovieFunction::HandleAsync
    events:
      - http:
          method: DELETE
          path: /movies/{movieId}
          authorizer: aws_iam
  GetMovies:
    handler: MovieApi::MovieApi.Functions.GetMoviesFunction::HandleAsync
    events:
      - http:
          method: GET
          path: /movies
          authorizer: aws_iam
  CreateMovie:
    handler: MovieApi::MovieApi.Functions.CreateMovieFunction::HandleAsync
    events:
      - http:
          method: POST
          path: /movies
          authorizer: aws_iam
          request:
            schemas:
              application/json:
                name: CreateMovieRequest
                schema: ${file(Schemas/CreateMovieRequest.schema.json)}
  GetMovieCharacters:
    handler: MovieApi::MovieApi.Functions.GetMovieCharactersFunction::HandleAsync
    events:
      - http:
          method: GET
          path: /movies/{movieId}/characters
          authorizer: aws_iam
  GetMovieDirectors:
    handler: MovieApi::MovieApi.Functions.GetMovieDirectorsFunction::HandleAsync
    events:
      - http:
          method: GET
          path: /movies/{movieId}/directors
          authorizer: aws_iam
  GetCharacterMovies:
    handler: MovieApi::MovieApi.Functions.GetCharacterMoviesFunction::HandleAsync
    events:
      - http:
          method: GET
          path: /characters/{characterId}/movies
          authorizer: aws_iam
  GetDirectorMovies:
    handler: MovieApi::MovieApi.Functions.GetDirectorMoviesFunction::HandleAsync
    events:
      - http:
          method: GET
          path: /directors/{directorId}/movies
          authorizer: aws_iam

resources:
  - ${file(./DynamoDb/MoviesTable.yml)}
  - Resources:
      ApiGatewayRestApi:
        Type: 'AWS::ApiGateway::RestApi'
        Properties:
          Name: MoviesApi